// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjqxNiB7ul0hd6ypdzvypUgyGi-krUI0k',
    appId: '1:1027161794103:web:db66c2103a5c26136841b2',
    messagingSenderId: '1027161794103',
    projectId: 'whales-a0b63',
    authDomain: 'whales-a0b63.firebaseapp.com',
    storageBucket: 'whales-a0b63.appspot.com',
    measurementId: 'G-62627BXM0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD68qSdeGoG9fK32U_OzjVYWiAVS7WCftA',
    appId: '1:1027161794103:android:d8864f310c72a9dd6841b2',
    messagingSenderId: '1027161794103',
    projectId: 'whales-a0b63',
    storageBucket: 'whales-a0b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXtmIaS2oIQiI2GdBiVd60ym4Fg5XzVas',
    appId: '1:1027161794103:ios:33d1fb81274c62666841b2',
    messagingSenderId: '1027161794103',
    projectId: 'whales-a0b63',
    storageBucket: 'whales-a0b63.appspot.com',
    iosClientId: '1027161794103-e1r5419rt328ergkq4jj686joledtker.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXtmIaS2oIQiI2GdBiVd60ym4Fg5XzVas',
    appId: '1:1027161794103:ios:336bef545dd1a0da6841b2',
    messagingSenderId: '1027161794103',
    projectId: 'whales-a0b63',
    storageBucket: 'whales-a0b63.appspot.com',
    iosClientId: '1027161794103-sd1kodrhhr9de1dc10v7sober75nq557.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatApp.RunnerTests',
  );
}
